name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Chequeo del codigo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Inicio de login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Final de login"
    - name: Docker Build Iamge
      run:
        docker build -t celsoarmas/docker-graphql:0.0.2 .
        docker build -t celsoarmas/docker-graphql .
    - name: Docker Push Image
      run:
        docker push  celsoarmas/docker-graphql:0.0.2
        docker push  celsoarmas/docker-graphql
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
